"""Generates plugin-chain/src/lcd/Hd44780RomA00.h and AxStartupStrip.h from
tools/lcd/a00_font.py and tools/lcd/strip-*.txt. Run from the project root:
    .venv/bin/python tools/lcd/gen_headers.py"""
import sys; sys.path.insert(0, 'tools/lcd')
from a00_font import A00
out = ["// GENERATED by tools/lcd/gen_headers.py -- do not edit by hand.",
       "// HD44780 character generator ROM, code A00, characters 0x20-0x7F.",
       "// 8 bytes per character, rows top to bottom, bit 4 = leftmost dot,",
       "// row 7 (cursor line) always 0. Verified against the AX300G start-up",
       "// videos of 2026-09-22 (docs/lcd-startup-2026-09-22.md).",
       "#pragma once", "#include <cstdint>", "namespace axlcd {",
       "static constexpr uint8_t kRomA00[96][8] = {"]
for c in range(0x20, 0x80):
    g = A00[c] + [0]
    ch = chr(c) if c not in (0x5C, 0x7E, 0x7F) else {0x5C: 'yen', 0x7E: 'right arrow', 0x7F: 'left arrow'}[c]
    out.append("    {" + ",".join(f"0x{b:02X}" for b in g) + "},  // " + f"0x{c:02X} {ch}")
out += ["};", "}  // namespace axlcd", ""]
open('plugin-chain/src/lcd/Hd44780RomA00.h', 'w').write('\n'.join(out))

def cells(path):
    rows = [l.strip() for l in open(path) if l.strip()]
    assert len(rows) == 16 and all(len(r) == 80 for r in rows)
    res = []
    for r in range(2):
        line = []
        for c in range(16):
            line.append([int(rows[r*8+i][c*5:c*5+5].replace('#', '1').replace('.', '0'), 2) for i in range(8)])
        res.append(line)
    return res
out = ["// GENERATED by tools/lcd/gen_headers.py -- do not edit by hand.",
       "// The start-up sweep's big-letter bitmap: 16 cells x 2 rows of 5x8 dots,",
       "// i.e. an 80x16 canvas drawn without the inter-cell gaps. The firmware",
       "// shows it through a 4-cell x 2-row window (the 8 CGRAM characters)",
       "// that steps right two cells at a time. kStripAX300G is the unit's own,",
       "// read dot-for-dot from both videos (they agree on all 1280 dots);",
       "// kStripAX330G replaces the first '0' with the unit's own '3', moved",
       "// 11 dots right (tools/lcd/strip-*.txt).",
       "#pragma once", "#include <cstdint>", "namespace axlcd {"]
for name, path in (("kStripAX300G", "tools/lcd/strip-ax300g-measured.txt"), ("kStripAX330G", "tools/lcd/strip-ax330g.txt")):
    cc = cells(path)
    out.append(f"static constexpr uint8_t {name}[2][16][8] = {{")
    for r in range(2):
        out.append("  {")
        for c in range(16):
            out.append("    {" + ",".join(f"0x{b:02X}" for b in cc[r][c]) + "},")
        out.append("  },")
    out.append("};")
out += ["}  // namespace axlcd", ""]
open('plugin-chain/src/lcd/AxStartupStrip.h', 'w').write('\n'.join(out))
print("ok")
